// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
    product_id?: (number | null);
    price?: (number | null);
    mrp?: (number | null);
    brand?: (string | null);
    product_url?: (string | null);
    image_url?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    product_id?: (number | null);
    price?: (number | null);
    mrp?: (number | null);
    brand?: (string | null);
    product_url?: (string | null);
    image_url?: (string | null);
    id: string;
    product_rating?: (number | null);
    product_rating_count?: (number | null);
    owner_id: string;
    owner_name?: (string | null);
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    product_id?: (number | null);
    price?: (number | null);
    mrp?: (number | null);
    brand?: (string | null);
    product_url?: (string | null);
    image_url?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReviewCreate = {
    title: string;
    description: string;
    rating: number;
    review_id?: (string | null);
    review_date?: (string | null);
    is_a_buyer?: (boolean | null);
    review_label?: (string | null);
    item_id: string;
};

export type ReviewPublic = {
    title: string;
    description: string;
    rating: number;
    review_id: string;
    review_date?: (string | null);
    is_a_buyer?: (boolean | null);
    review_label?: (string | null);
    id: string;
    owner_id: string;
    owner_name?: (string | null);
    item_id: string;
    item_title?: (string | null);
    created_at?: (string | null);
};

export type ReviewsPublic = {
    data: Array<ReviewPublic>;
    count: number;
};

export type ReviewUpdate = {
    title?: (string | null);
    description?: (string | null);
    rating?: (number | null);
};

export type TagBase = {
    name: string;
};

export type TagCreate = {
    name: string;
};

export type TagPublic = {
    name: string;
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    pro_user?: (boolean | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    pro_user?: (boolean | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    pro_user?: (boolean | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsSearchItemsData = {
    keyword: string;
    limit?: number;
    skip?: number;
};

export type ItemsSearchItemsResponse = (ItemsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReviewsGetReviewsByItemData = {
    itemId: string;
    limit?: number;
    skip?: number;
};

export type ReviewsGetReviewsByItemResponse = (ReviewsPublic);

export type ReviewsCreateReviewData = {
    itemId: string;
    requestBody: ReviewCreate;
};

export type ReviewsCreateReviewResponse = (ReviewPublic);

export type ReviewsReadReviewsData = {
    limit?: number;
    skip?: number;
};

export type ReviewsReadReviewsResponse = (ReviewsPublic);

export type ReviewsUpdateReviewData = {
    requestBody: ReviewUpdate;
    reviewId: string;
};

export type ReviewsUpdateReviewResponse = (ReviewPublic);

export type ReviewsDeleteReviewData = {
    reviewId: string;
};

export type ReviewsDeleteReviewResponse = ({
    [key: string]: unknown;
});

export type TagsGetAllTagsResponse = (Array<TagPublic>);

export type TagsCreateTagData = {
    requestBody: TagCreate;
};

export type TagsCreateTagResponse = (TagPublic);

export type TagsAddTagToItemData = {
    itemId: string;
    tagId: string;
};

export type TagsAddTagToItemResponse = ({
    [key: string]: unknown;
});

export type TagsRemoveTagFromItemData = {
    itemId: string;
    tagId: string;
};

export type TagsRemoveTagFromItemResponse = ({
    [key: string]: unknown;
});

export type TagsUpdateTagData = {
    requestBody: TagBase;
    tagId: string;
};

export type TagsUpdateTagResponse = (TagPublic);

export type TagsDeleteTagData = {
    tagId: string;
};

export type TagsDeleteTagResponse = ({
    [key: string]: unknown;
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);