"""add predicted_is_a_buyer to review

Revision ID: 778b09ca48e8
Revises: 8f1d2b7c4a10
Create Date: 2026-05-10 03:43:14.146505

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '778b09ca48e8'
down_revision = '8f1d2b7c4a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
